In [19]:
from tensorflow.keras.preprocessing.text import one_hot

In [20]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [21]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [22]:
## Define the vocabulary size
voc_size=10000

In [23]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [24]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[165, 5265, 3072, 460],
 [165, 5265, 3072, 3957],
 [165, 7468, 3072, 1064],
 [3833, 8068, 1754, 2613, 9627],
 [3833, 8068, 1754, 2613, 9338],
 [6238, 165, 4082, 3072, 5599],
 [1567, 6973, 436, 2613]]

In [25]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [26]:
import numpy as np

In [27]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  165 5265 3072  460]
 [   0    0    0    0  165 5265 3072 3957]
 [   0    0    0    0  165 7468 3072 1064]
 [   0    0    0 3833 8068 1754 2613 9627]
 [   0    0    0 3833 8068 1754 2613 9338]
 [   0    0    0 6238  165 4082 3072 5599]
 [   0    0    0    0 1567 6973  436 2613]]


In [28]:
# feature representation
dim=10

In [34]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [35]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 282ms/step


array([[[ 0.02441857,  0.04878857,  0.03439215,  0.03653489,
         -0.00081754,  0.04648231,  0.02881325, -0.03995872,
         -0.02827611,  0.04363379],
        [ 0.02441857,  0.04878857,  0.03439215,  0.03653489,
         -0.00081754,  0.04648231,  0.02881325, -0.03995872,
         -0.02827611,  0.04363379],
        [ 0.02441857,  0.04878857,  0.03439215,  0.03653489,
         -0.00081754,  0.04648231,  0.02881325, -0.03995872,
         -0.02827611,  0.04363379],
        [ 0.02441857,  0.04878857,  0.03439215,  0.03653489,
         -0.00081754,  0.04648231,  0.02881325, -0.03995872,
         -0.02827611,  0.04363379],
        [-0.03860954,  0.00768982, -0.00915866, -0.04914285,
         -0.01895973,  0.02040274,  0.04474452, -0.01948121,
         -0.02553645, -0.04997198],
        [-0.01201405,  0.04952444, -0.03108541,  0.00731438,
          0.0081645 ,  0.01868755, -0.04737614,  0.00982847,
          0.04337169, -0.04997513],
        [-0.02958236,  0.00524534,  0.03865173, -0.0

In [32]:
embedded_docs[0]

array([   0,    0,    0,    0,  165, 5265, 3072,  460])

In [36]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step


array([[-0.04569553, -0.00374721,  0.03007727,  0.03262367,  0.02896041,
         0.03375955, -0.00567893, -0.02268981,  0.02837941,  0.03892599],
       [-0.04569553, -0.00374721,  0.03007727,  0.03262367,  0.02896041,
         0.03375955, -0.00567893, -0.02268981,  0.02837941,  0.03892599],
       [-0.04569553, -0.00374721,  0.03007727,  0.03262367,  0.02896041,
         0.03375955, -0.00567893, -0.02268981,  0.02837941,  0.03892599],
       [-0.04569553, -0.00374721,  0.03007727,  0.03262367,  0.02896041,
         0.03375955, -0.00567893, -0.02268981,  0.02837941,  0.03892599],
       [-0.04685539,  0.03536964, -0.03291631,  0.04602348, -0.02406183,
        -0.00706907, -0.04648988,  0.00106102,  0.00630959,  0.04084483],
       [ 0.01568458,  0.03145567,  0.04781205,  0.03856982, -0.03733411,
        -0.04772812,  0.02066663, -0.00454979, -0.01415924,  0.01010158],
       [-0.02007324,  0.04311613, -0.04930569,  0.04392009,  0.01136384,
        -0.03206515,  0.02274462,  0.04842718